const {chromium}=require('@playwright/test');const fs=require('node:fs'),path=require('node:path');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(root,'build','qa');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'msedge',headless:true});const results=[];
for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]]){
  const page=await browser.newPage({viewport:{width,height}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.join(root,'index.html').replaceAll('\\','/'));await page.waitForFunction(()=>document.querySelectorAll('.lesson-choice').length===8);await page.locator('video').evaluate(v=>new Promise((resolve,reject)=>{if(v.readyState>=1)return resolve();v.addEventListener('loadedmetadata',resolve,{once:true});v.addEventListener('error',()=>reject(new Error('metadata failure')),{once:true})}));
  const dims=await page.evaluate(()=>({body:document.documentElement.scrollWidth,viewport:innerWidth}));if(dims.body>width+1)throw new Error('Horizontal overflow: '+JSON.stringify(dims));
  const probe=await page.locator('video').evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight}));if(probe.width!==1920||probe.height!==1080||probe.duration<120)throw new Error('Bad video metadata');
  await page.locator('#first-draft').fill('Lower fares may encourage some commuters to use buses.');await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('已保存'));
  await page.locator('#next').click();await page.locator('#previous').click();if(!(await page.locator('#first-draft').inputValue()).includes('Lower fares'))throw new Error('Draft not restored across lesson selection');
  await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.lesson-choice').length===8);if(!(await page.locator('#first-draft').inputValue()).includes('Lower fares'))throw new Error('Draft not restored after reload');
  await page.locator('#tab-script').click();if(!(await page.locator('#panel-script').isVisible()))throw new Error('Script tab failed');await page.locator('#tab-script').press('ArrowRight');if(!(await page.locator('#panel-sources').isVisible()))throw new Error('Keyboard tab navigation failed');await page.locator('#tab-practice').click();
  await page.locator('#answer-details summary').click();if(!(await page.locator('#answer').isVisible()))throw new Error('Answer reveal failed');await page.locator('#answer-details summary').click();
  await page.locator('#complete-lesson').click();if(!(await page.locator('#completion-total').innerText()).includes('1 / 8'))throw new Error('Completion failed');await page.locator('#complete-lesson').click();
  await page.locator('#first-draft').fill('');await page.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('已保存'));await page.locator('#first-draft').blur();
  await page.locator('#chapter-list button').nth(1).click();await page.waitForFunction(()=>document.querySelector('video').currentTime>20);await page.locator('video').evaluate(v=>new Promise(resolve=>{v.pause();v.addEventListener('seeked',()=>requestAnimationFrame(()=>requestAnimationFrame(resolve)),{once:true});v.currentTime=0}));await page.waitForFunction(()=>document.querySelector('video').readyState>=2&&!document.querySelector('video').seeking);await page.evaluate(()=>window.scrollTo(0,0));
  await page.locator('video').evaluate(v=>v.play());await page.waitForFunction(()=>document.querySelector('video').currentTime>.7);await page.locator('video').evaluate(v=>v.pause());await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});if(errors.length)throw new Error(errors.join('\n'));results.push({name,width,metadata:probe,drafts:'saved and restored',tabs:'mouse and keyboard pass',answers:'pass',chapters:'seek pass',overflow:'none',runtimeErrors:errors});await page.close();
}
const failurePage=await browser.newPage({viewport:{width:1440,height:1000}});await failurePage.addInitScript(()=>{Storage.prototype.getItem=function(){throw new DOMException('blocked','SecurityError')};Storage.prototype.setItem=function(){throw new DOMException('blocked','SecurityError')}});await failurePage.goto('file:///'+path.join(root,'index.html').replaceAll('\\','/'));await failurePage.waitForFunction(()=>document.querySelectorAll('.lesson-choice').length===8);if(!(await failurePage.locator('#save-status').innerText()).includes('无法读取'))throw new Error('Read error was hidden on startup');await failurePage.locator('#first-draft').fill('A test draft kept in memory.');await failurePage.waitForFunction(()=>document.querySelector('#save-status').textContent.includes('保存失败'));await failurePage.locator('#next').click();if(!(await failurePage.locator('#save-status').innerText()).includes('保存失败'))throw new Error('Storage error hidden after selection');results.push({name:'storage-unavailable',startup:'read error visible',editing:'save error visible',lessonSelection:'error retained',export:'available'});await failurePage.close();await browser.close();fs.writeFileSync(path.join(out,'player-checks.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));})();
