/* data-jijing.js — 机经·考场真题回忆模块（补充批次）
 * 收录 2023-2026 考场考生回忆题目，供练习参考；标注近似的考试时间与考区（如有）。
 * 与 data-questions-recent.js（78 道）同属「机经」题源；训练营/题库可按题源切换。
 * T1 机经为文字描述版图表（无原图，用于练审题、结构与数据语言组织）。
 */
const JijingQuestions = [
  { src: "机经 2026年5月", t2type: "discussion", year: 2026,
    t2: "Some people think that the government should decide what subjects students study at university, while others believe that students should be free to choose their own area of study. Discuss both these views and give your own opinion." },
  { src: "机经 2026年4月", t2type: "opinion", year: 2026,
    t2: "In many parts of the world, people are choosing to have fewer children or none at all. Do you think this is a positive or negative trend?" },
  { src: "机经 2026年3月", t2type: "two-part", year: 2026,
    t2: "Nowadays many people suffer from stress because of their busy lifestyles. What are the main causes of stress in modern life? How can this problem be dealt with?" },
  { src: "机经 2026年2月", t2type: "adv-disadv-opinion", year: 2026,
    t2: "More and more companies are allowing employees to work from home. Do you think the advantages of working from home outweigh the disadvantages?" },
  { src: "机经 2026年1月", t2type: "opinion", year: 2026,
    t2: "Some people believe that arts such as music and painting should be taught in every school as compulsory subjects. To what extent do you agree or disagree?" },
  { src: "机经 2025年12月", t2type: "discussion", year: 2025,
    t2: "Some people say that the best way to protect the environment is to use fewer resources in daily life, while others think that governments and large companies hold the key to solving environmental problems. Discuss both these views and give your own opinion." },
  { src: "机经 2025年11月", t2type: "two-part", year: 2025,
    t2: "In many countries, people are choosing to buy products from international brands rather than local ones. What problems can this trend cause? How can local businesses respond to it?" },
  { src: "机经 2025年10月", t2type: "opinion", year: 2025,
    t2: "Some people believe that professional athletes are good role models for young people, whereas others think they set a poor example. Do you agree or disagree that sports stars make good role models?" },
  { src: "机经 2025年9月", t2type: "adv-disadv-opinion", year: 2025,
    t2: "An increasing number of schools are using artificial intelligence tools to mark students' homework and exams. Do you think the benefits of this development outweigh the drawbacks?" },
  { src: "机经 2025年8月", t2type: "two-part", year: 2025,
    t2: "These days, many people prefer to watch films on their phones or tablets rather than go to the cinema. Why has this change happened? What can cinema owners do to attract audiences back?" },
  { src: "机经 2025年7月", t2type: "opinion", year: 2025,
    t2: "Some people think that universities should only accept applicants with the highest examination results, while others believe that admission should also consider students' personalities and potential. To what extent do you agree or disagree?" },
  { src: "机经 2025年6月", t2type: "discussion", year: 2025,
    t2: "Some people argue that individuals should take full responsibility for their own health, while others think that governments should ensure their citizens stay healthy. Discuss both these views and give your own opinion." },
  { src: "机经 2025年5月", t2type: "two-part", year: 2025,
    t2: "In many cities, an increasing number of people do not know their neighbours, and the sense of community is being lost. What are the causes of this trend? How can residents and communities build stronger local connections?" },
  { src: "机经 2025年4月", t2type: "opinion", year: 2025,
    t2: "Some people think that children should start learning a foreign language as soon as they begin primary school, rather than in secondary school. Do the advantages of this approach outweigh the disadvantages?" },
  { src: "机经 2025年3月", t2type: "two-part", year: 2025,
    t2: "More and more tasks at home and at work are being performed by robots. Why is this happening? Is it a positive or negative development?" },
  { src: "机经 2025年2月", t2type: "discussion", year: 2025,
    t2: "Some people believe that famous people's private lives should be respected by the media, while others think that public figures should accept media attention as part of their success. Discuss both these views and give your own opinion." },
  { src: "机经 2025年1月", t2type: "opinion", year: 2025,
    t2: "Libraries are seen by some as no longer necessary because digital technology has replaced the need for printed books. To what extent do you agree or disagree?" },
  { src: "机经 2024年12月", t2type: "adv-disadv-opinion", year: 2024,
    t2: "Online shopping is replacing shopping in physical stores in many countries. Do you think this development is more positive or more negative for consumers and society?" },
  { src: "机经 2024年11月", t2type: "two-part", year: 2024,
    t2: "In spite of a wide range of sports facilities available, many people do not exercise enough nowadays. What are the reasons for this? What can be done to encourage people to exercise more?" },
  { src: "机经 2024年10月", t2type: "opinion", year: 2024,
    t2: "Some people think that employers should give staff at least four weeks of holiday per year to improve their job performance. To what extent do you agree or disagree?" },
  { src: "机经 2024年9月", t2type: "discussion", year: 2024,
    t2: "Some people believe that it is the responsibility of schools to teach children how to be good members of society, while others think parents should teach children this. Discuss both these views and give your own opinion." },
  { src: "机经 2024年8月", t2type: "adv-disadv", year: 2024,
    t2: "Nowadays many young people choose to take a gap year before starting university. What are the advantages and disadvantages of this trend for the students themselves?" },
  { src: "机经 2024年7月", t2type: "two-part", year: 2024,
    t2: "Many historic buildings are being destroyed or replaced by new structures. What are the reasons for this? What are the consequences of losing historic buildings?" },
  { src: "机经 2024年6月", t2type: "opinion", year: 2024,
    t2: "Some people think that the increasing use of cars has had a negative effect on the quality of life in cities, and that bicycles should replace cars for short journeys. To what extent do you agree or disagree?" },
  { src: "机经 2024年5月", t2type: "adv-disadv-opinion", year: 2024,
    t2: "These days, many people work for the same company all their lives, while others prefer to change jobs frequently. Do you think staying with one employer has more advantages than changing jobs?" },
  { src: "机经 2024年4月", t2type: "two-part", year: 2024,
    t2: "In many countries, traditional festivals are becoming less popular among young people. Why is this happening? How important is it to preserve traditional festivals?" },
  { src: "机经 2024年3月", t2type: "discussion", year: 2024,
    t2: "Some people think that new houses should be built in the same style as older existing houses in the local area, while others believe that people should be allowed to build houses in the style they prefer. Discuss both these views and give your own opinion." },
  { src: "机经 2024年2月", t2type: "opinion", year: 2024,
    t2: "Some people believe that companies should provide sports and social facilities for their employees, while others think this is an unnecessary expense. To what extent do you agree or disagree?" },
  { src: "机经 2024年1月", t2type: "adv-disadv-opinion", year: 2024,
    t2: "An increasing number of people are choosing to study online rather than attend classes in person. Do you think the advantages of online education outweigh the disadvantages?" },
  { src: "机经 2023年12月", t2type: "two-part", year: 2023,
    t2: "Nowadays, many people spend less and less time at home. What are the reasons for this? What effects does this have on individuals and society?" },
  { src: "机经 2023年11月", t2type: "opinion", year: 2023,
    t2: "Some people think that the money spent on protecting wild animals should be used for solving human problems instead. To what extent do you agree or disagree?" },
  { src: "机经 2023年10月", t2type: "discussion", year: 2023,
    t2: "Some people say that economic growth is the only way to end world poverty and hunger, while others insist that economic growth is causing damage to the environment and should be slowed down. Discuss both these views and give your own opinion." },
  { src: "机经 2023年9月", t2type: "adv-disadv-opinion", year: 2023,
    t2: "In many workplaces, employees are now allowed to dress casually instead of wearing formal uniforms or suits. Do you think the advantages of casual dress codes outweigh the disadvantages?" },

  { src: "机经 2026年3月 T1", t1type: "line graph", year: 2026, task1: true,
    t1: "（机经·文字描述）线图：某国 2000-2024 年三种通勤方式（私家车、公交、自行车）在全部通勤中所占百分比的变化。私家车从约 55% 一路上升到约 70%；公交从约 25% 波动下降到约 15%；自行车先从约 20% 降到约 10%（2010 年前后），随后回升到约 15%。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2026年1月 T1", t1type: "bar chart", year: 2026, task1: true,
    t1: "（机经·文字描述）柱图：五个欧洲国家 2023 年在图书馆、电影院和健身中心三类场所的月均到访人次。德国三类均领先（图书馆约 40、电影院约 55、健身中心约 45）；意大利和西班牙图书馆到访最低（约 10-12）；英国的健身中心到访高于图书馆。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2025年10月 T1", t1type: "maps", year: 2025, task1: true,
    t1: "（机经·文字描述）地图：某小镇中心 2005 年与今天的变化。2005 年镇中心有市场广场、公交站和一片农田；今天农田被改建为住宅区，市场广场变为停车场，新增一条环路与两处购物中心，公交站移至环路旁。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2025年6月 T1", t1type: "table", year: 2025, task1: true,
    t1: "（机经·文字描述）表格：四个国家 2010 年与 2020 年可再生能源占全部能源消耗的比例。A 国从 12% 升至 30%；B 国从 45% 微升至 48%；C 国从 8% 升至 22%；D 国从 25% 降至 18%。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2025年2月 T1", t1type: "process diagram", year: 2025, task1: true,
    t1: "（机经·文字描述）流程图：雨水如何被收集净化为饮用水。共六个阶段：雨水落在屋顶 → 沿管道汇入蓄水池 → 经过滤网去除树叶等杂质 → 进入沙石过滤层 → 加入化学品消毒 → 储存在水箱中供家庭使用。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2024年11月 T1", t1type: "pie chart", year: 2024, task1: true,
    t1: "（机经·文字描述）两张饼图：某大学 2005 年与 2025 年学生经费来源构成。2005 年：家庭支付 55%、政府资助 30%、兼职收入 15%；2025 年：兼职收入 35%、政府资助 30%、家庭支付 20%、奖学金 15%。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2024年6月 T1", t1type: "line graph", year: 2024, task1: true,
    t1: "（机经·文字描述）线图：1970-2020 年某城市五类案件数量的变化。入室盗窃始终最高（约 4500 起降至 3000 起）；抢劫先升后降；汽车盗窃在 1990 年达到峰值后显著下降；诈骗类从 2000 年起快速上升；人身伤害类保持平稳。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." },
  { src: "机经 2023年12月 T1", t1type: "bar chart", year: 2023, task1: true,
    t1: "（机经·文字描述）柱图：某国 2005、2015 和 2025 年男女性在四个教育阶段（高中、本科、硕士、博士）的入学人数。本科人数最多且女性略高；硕士与博士阶段男性人数下降、女性持续上升；高中阶段两性均小幅下降。Summarise the information by selecting and reporting the main features, and make comparisons where relevant." }
];
