'use strict';
(() => {
  const data=window.COURSE, media=window.COURSE_MEDIA, sources=window.COURSE_SOURCES;
  const $=id=>document.getElementById(id), key='iwc_course_simon_after_v1';
  let state={drafts:{},completed:[]}, index=0, saving, storageError='';
  try { const raw=JSON.parse(localStorage.getItem(key)||'null'); if(raw&&raw.drafts&&Array.isArray(raw.completed))state=raw; } catch (_) { storageError='无法读取本机记录；请用导出保存练习。'; $('save-status').textContent=storageError; }
  const mm=seconds=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
  function persist(){try{localStorage.setItem(key,JSON.stringify(state));storageError='';$('save-status').textContent='已保存到本机浏览器';return true}catch(_){storageError='保存失败，请导出本课练习。';$('save-status').textContent=storageError;return false}}
  function save(){const id=data.lessons[index].id;state.drafts[id]={first:$('first-draft').value,revision:$('revision').value,priority:$('priority').value,updated:new Date().toISOString()};persist()}
  function updateCount(){$('word-count').textContent=`${($('first-draft').value.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g)||[]).length} 个英文词`}
  function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node}
  function renderNav(){const nav=$('lesson-list');nav.replaceChildren();data.lessons.forEach((lesson,i)=>{const m=media.lessons.find(x=>x.id===lesson.id),b=el('button',undefined,'lesson-choice');b.type='button';b.setAttribute('aria-current',String(i===index));b.append(el('span',lesson.id,'ordinal'));const label=el('span');label.append(el('span',lesson.title,'choice-title'),el('span',`${mm(m.duration_seconds)} · ${state.completed.includes(lesson.id)?'练习已完成':'待练习'}`,'choice-meta'));b.append(label);b.addEventListener('click',()=>select(i));nav.append(b)});$('completion-total').textContent=`${state.completed.length} / 8 课练习已完成`}
  function select(next,initial=false){if(!initial){clearTimeout(saving);save()} index=next;const l=data.lessons[index],m=media.lessons.find(x=>x.id===l.id);$('lesson-title').textContent=l.title;$('lesson-goal').textContent=l.goal;$('lesson-number').textContent=`第 ${l.id} / 08 课`;$('lesson-duration').textContent=`${mm(m.duration_seconds)} · ${m.chapters.length} 个章节`;
    const v=$('lesson-video');v.pause();v.replaceChildren();v.src=m.video;v.poster=m.poster;v.load();$('video-error').hidden=true;
    $('download-video').href=m.video;$('download-captions').href=`media/lesson-${l.id}.srt`;
    const chapters=$('chapter-list');chapters.replaceChildren();m.chapters.forEach((ch,i)=>{const b=el('button');b.type='button';b.append(el('span',ch.title),el('time',mm(ch.start)));b.setAttribute('aria-label',`${ch.title}，跳到 ${mm(ch.start)}`);b.addEventListener('click',()=>{if(v.readyState>=1){v.currentTime=ch.start;v.play().catch(()=>{})}else{const seek=()=>{v.currentTime=ch.start;v.play().catch(()=>{})};v.addEventListener('loadedmetadata',seek,{once:true});v.load()}});chapters.append(b)});
    $('exercise').textContent=l.exercise;$('answer').textContent=l.answer;$('transfer').textContent=l.transfer;$('rubric').replaceChildren(...l.rubric.map(x=>el('li',x)));$('answer-details').open=false;$('full-example').hidden=!['07','08'].includes(l.id);$('full-example').href=`handbook.html#${l.id==='07'?'report':'essay'}`;
    const draft=state.drafts[l.id]||{};$('first-draft').value=draft.first||'';$('revision').value=draft.revision||'';$('priority').value=draft.priority||'';updateCount();$('save-status').textContent=storageError||(draft.updated?'已恢复本课练习':'初稿保存在本机浏览器');
    const script=$('script');script.replaceChildren();l.scenes.forEach((s,i)=>{script.append(el('h2',s.title));s.lines.forEach(row=>script.append(el('p',row.text,row.lang==='en'?'script-example':'')));s.narration.forEach(n=>script.append(el('p',n.text,n.lang==='en-GB'?'script-example':'')))});
    const src=$('sources');src.replaceChildren();l.sources.forEach(id=>{const s=sources.sources.find(x=>x.id===id);if(!s)return;const block=el('article',undefined,'source-item'),h=el('h3');if(s.url){const a=el('a',s.title);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';h.append(a)}else h.textContent=s.title;block.append(h,el('p',s.status),el('p',s.use));src.append(block)});
    $('complete-lesson').textContent=state.completed.includes(l.id)?'撤销完成标记':'标记练习已完成';$('previous').disabled=index===0;$('next').disabled=index===data.lessons.length-1;renderNav();activateTab('practice');
    try{history.replaceState(null,'',`#lesson-${l.id}`)}catch(_){} if(!initial)$('lesson-title').focus({preventScroll:true});
  }
  function activateTab(name){['practice','script','sources'].forEach(x=>{const b=$('tab-'+x),active=x===name;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$('panel-'+x).hidden=!active})}
  ['practice','script','sources'].forEach((x,i)=>{const b=$('tab-'+x);b.addEventListener('click',()=>activateTab(x));b.addEventListener('keydown',e=>{const names=['practice','script','sources'];if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;activateTab(names[n]);$('tab-'+names[n]).focus()}})});
  ['first-draft','revision','priority'].forEach(id=>$(id).addEventListener('input',()=>{updateCount();$('save-status').textContent='正在保存…';clearTimeout(saving);saving=setTimeout(save,350)}));window.addEventListener('beforeunload',save);
  $('export-draft').addEventListener('click',()=>{save();const l=data.lessons[index],out={course:data.title,lesson:l.id,title:l.title,prompt:l.exercise,draft:state.drafts[l.id],completionIsNotScore:true};const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json;charset=utf-8'})),a=el('a');a.href=url;a.download=`simon-after-lesson-${l.id}-practice.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)});
  $('complete-lesson').addEventListener('click',()=>{save();const l=data.lessons[index];if(state.completed.includes(l.id))state.completed=state.completed.filter(x=>x!==l.id);else{if(!$('first-draft').value.trim()){$('completion-note').textContent='请先留下独立初稿，再标记练习完成。';$('first-draft').focus();return}state.completed.push(l.id)}persist();$('completion-note').textContent='完成记录不代表达到某个分数；请继续换题复测。';$('complete-lesson').textContent=state.completed.includes(l.id)?'撤销完成标记':'标记练习已完成';renderNav()});
  $('previous').addEventListener('click',()=>select(Math.max(0,index-1)));$('next').addEventListener('click',()=>select(Math.min(data.lessons.length-1,index+1)));
  $('lesson-video').addEventListener('error',()=>{$('video-error').textContent='视频未能载入。请确认 media 文件夹与本页面在一起，或使用下方下载链接打开视频；逐字稿和练习仍可使用。';$('video-error').hidden=false});
  $('lesson-video').addEventListener('timeupdate',()=>{const m=media.lessons.find(x=>x.id===data.lessons[index].id);const active=m.chapters.findLastIndex(ch=>ch.start<=$('lesson-video').currentTime);[...$('chapter-list').children].forEach((b,i)=>b.setAttribute('aria-current',String(i===active)))});
  $('course-summary').textContent=`8 课 · ${Math.round(media.total_seconds/60)} 分钟 · 练习与讲评`;
  const road=$('roadmap-list');for(const stage of [...new Set(data.curriculum.slice(8).map(x=>x.stage))]){road.append(el('h3',stage));const list=el('ol');list.start=Number(data.curriculum.find(x=>x.stage===stage).id);data.curriculum.filter(x=>x.stage===stage).forEach(x=>list.append(el('li',x.title)));road.append(list)}
  const requested=location.hash.match(/lesson-(\d+)/),found=requested?data.lessons.findIndex(x=>x.id===requested[1]):-1;select(found>=0?found:0,true);
})();
